version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env 
    volumes:
      - ./videos:/app/videos
    command: >
      sh -c "export FAL_KEY=$FAL_API_KEY && flask run --host=0.0.0.0 --port=5000"
